[msg SYS_AUTO_RECOVER [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Auto-Recover?[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_HP_FULL [DEV: System MES]]
[uf 0 5 65278][uf 2 1]All party members are at full health.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_NO_SKIL [DEV: System MES]]
[uf 0 5 65278][uf 2 1]There are no party members with healing skills.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_SP_LESS [DEV: System MES]]
[uf 0 5 65278][uf 2 1]There is not enough SP for Auto-Recover.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_SP_LESS_2 [DEV: System MES]]
[uf 0 5 65278][uf 2 1]Ran out of SP to use a healing skill. Auto-Recover will be canceled.[n][uf 1 1][e]

[msg Mod_Menu_Text]
[uf 0 5 65278][uf 2 1]Mod Menu[uf 1 1][e]

[msg Mod_Menu_Text]
[uf 0 5 65278][uf 2 1]Select a menu[uf 1 1][e]

[sel Mod_Menu_Options top]
[uf 0 5 65278][uf 2 1]Original Function[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Fast Travel[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Facility Menu[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Menu[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Player Menu[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Flags and Counters[uf 1 1][e]

[msg Menu_Text]
[uf 0 5 65278][uf 2 1]Select an option[uf 1 1][e]

[msg Call_Menu_Text]
[uf 0 5 65278][uf 2 1]Call Menu[uf 1 1][e]

[sel Call_Menu]
[uf 0 5 65278][uf 2 1]Call Field[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Event[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Social Link Event[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Key Free Event[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Battle[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Dungeon[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call Movie[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Call BGM[uf 1 1][e]

[msg Player_Menu_Text]
[uf 0 5 65278][uf 2 1]Player Menu[uf 1 1][e]

[sel Player_Menu]
[uf 0 5 65278][uf 2 1]Persona Editor[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Change Name[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Change Date[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Change Yen[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Change Items[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Add Party Member[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Remove Party Member[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Max HP/SP[uf 1 1][e]

[sel Options_Digits]
[uf 0 5 65278][uf 2 1]0[uf 1 1][e]
[uf 0 5 65278][uf 2 1]1[uf 1 1][e]
[uf 0 5 65278][uf 2 1]2[uf 1 1][e]
[uf 0 5 65278][uf 2 1]3[uf 1 1][e]
[uf 0 5 65278][uf 2 1]4[uf 1 1][e]
[uf 0 5 65278][uf 2 1]5[uf 1 1][e]
[uf 0 5 65278][uf 2 1]6[uf 1 1][e]
[uf 0 5 65278][uf 2 1]7[uf 1 1][e]
[uf 0 5 65278][uf 2 1]8[uf 1 1][e]
[uf 0 5 65278][uf 2 1]9[uf 1 1][e]

[msg Digit_Text]
[uf 0 5 65278][uf 2 1]Select [uf 2 4 0][uf 1 1][e]

[msg Major_Id_Text]
[uf 0 5 65278][uf 2 1]Major ID Input[uf 1 1][e]

[msg Minor_Id_Text]
[uf 0 5 65278][uf 2 1]Minor ID Input[uf 1 1][e]

[msg Parts_Text]
[uf 0 5 65278][uf 2 1]Parts ID Input[uf 1 1][e]

[sel Months]
[uf 0 5 65278][uf 2 1]January[uf 1 1][e]
[uf 0 5 65278][uf 2 1]February[uf 1 1][e]
[uf 0 5 65278][uf 2 1]March[uf 1 1][e]
[uf 0 5 65278][uf 2 1]April[uf 1 1][e]
[uf 0 5 65278][uf 2 1]May[uf 1 1][e]
[uf 0 5 65278][uf 2 1]June[uf 1 1][e]
[uf 0 5 65278][uf 2 1]July[uf 1 1][e]
[uf 0 5 65278][uf 2 1]August[uf 1 1][e]
[uf 0 5 65278][uf 2 1]September[uf 1 1][e]
[uf 0 5 65278][uf 2 1]October[uf 1 1][e]
[uf 0 5 65278][uf 2 1]November[uf 1 1][e]
[uf 0 5 65278][uf 2 1]December[uf 1 1][e]

[msg Month_Text]
[uf 0 5 65278][uf 2 1]Select a month[uf 1 1][e]

[msg Date_Text]
[uf 0 5 65278][uf 2 1]Change Date[uf 1 1][e]

[msg Day_Text]
[uf 0 5 65278][uf 2 1]Input Day[uf 1 1][e]

[msg Yen_Text]
[uf 0 5 65278][uf 2 1]Input Yen[uf 1 1][e]

[msg Movie_Text]
[uf 0 5 65278][uf 2 1]Input Movie ID[uf 1 1][e]

[msg BGM_Text]
[uf 0 5 65278][uf 2 1]Input BGM ID[uf 1 1][e]

[msg Dungeon_Text]
[uf 0 5 65278][uf 2 1]Input Dungeon Floor[uf 1 1][e]

[sel Facility_Menu]
[uf 0 5 65278][uf 2 1]Velvet Room[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Police Station[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Aohige Pharmacy[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Mayoido Antiques[uf 1 1][e]

[msg Facility_Menu_Text]
[uf 0 5 65278][uf 2 1]Facility Menu[uf 1 1][e]

[msg Item_Text]
[uf 0 5 65278][uf 2 1]Input Item ID[uf 1 1][e]

[msg Item_Confirmation_Text]
[uf 0 5 65278][uf 2 1]Selected item: [uf 4 4 1 37 1 0] x [uf 2 4 1][uf 1 1][e]

[msg Item_Number_Text]
[uf 0 5 65278][uf 2 1]Input Number of Items[uf 1 1][e]

[sel Confirmation]
[uf 0 5 65278][uf 2 1]Confirm[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Cancel[uf 1 1][e]

[sel Flag_Menu]
[uf 0 5 65278][uf 2 1]Toggle Flag[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Edit Counter[uf 1 1][e]

[msg Flag_Menu_Text]
[uf 0 5 65278][uf 2 1]Flag Menu[uf 1 1][e]

[sel On_Off]
[uf 0 5 65278][uf 2 1]On[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Off[uf 1 1][e]

[msg Flag_Indicator]
[uf 0 5 65278][uf 2 1]Flag [uf 2 4 0] is set to [uf 2 4 1][uf 1 1][e]

[msg Counter_Indicator]
[uf 0 5 65278][uf 2 1]Counter [uf 2 4 0] is set to [uf 2 4 1][uf 1 1][e]

[msg Flag_Text]
[uf 0 5 65278][uf 2 1]Input Flag ID[uf 1 1][e]

[msg Counter_Text]
[uf 0 5 65278][uf 2 1]Input Counter ID[uf 1 1][e]

[msg Number_Text]
[uf 0 5 65278][uf 2 1]Input Number[uf 1 1][e]

[msg Member_Text]
[uf 0 5 65278][uf 2 1]Select Member[uf 1 1][e]

[msg Member_List_Text]
[uf 0 5 65278][uf 2 1]Member List[uf 1 1][e]

[sel Member_List]
[uf 0 5 65278][uf 2 1]Yukari[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Junpei[uf 4 27 3 0][e]
[uf 0 5 65278][uf 2 1]Akihiko[uf 4 27 4 0][e]
[uf 0 5 65278][uf 2 1]Mitsuru[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Aigis[uf 4 27 7 0][e]
[uf 0 5 65278][uf 2 1]Ken[uf 4 27 8 0][e]
[uf 0 5 65278][uf 2 1]Koromaru[uf 4 27 9 0][e]
[uf 0 5 65278][uf 2 1]Shinjiro[uf 4 27 10 0][e]

[sel Item_Type_List]
[uf 0 5 65278][uf 2 1]Weapons[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Armor (Body)[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Armor (Footwear)[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Accessories[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Consumables[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Key Items[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Materials[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Skill Cards[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Outfits[uf 1 1][e]

[msg Item_Type_Text]
[uf 0 5 65278][uf 2 1]Select Item Type[uf 1 1][e]

[msg Item_Types_Text]
[uf 0 5 65278][uf 2 1]Item Types[uf 1 1][e]

[sel Social_Stat_List]
[uf 0 5 65278][uf 2 1]Academics[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Charm[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Courage[uf 1 1][e]

[msg Social_Stat_Text]
[uf 0 5 65278][uf 2 1]Select Social Stat[uf 1 1][e]

[msg Social_Stats_Text]
[uf 0 5 65278][uf 2 1]Social Stats[uf 1 1][e]

[msg Social_Stats_Increase_Text]
[uf 0 5 65278][uf 2 1]Increase by how much?[uf 1 1][e]

[sel Persona_Editor_List]
[uf 0 5 65278][uf 2 1]Add Persona[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Delete All Current Personas[uf 1 1][e]
[uf 0 5 65278][uf 2 1]Evolve Member's Persona[uf 1 1][e]

[msg Persona_Editor_Text]
[uf 0 5 65278][uf 2 1]Persona Editor[uf 1 1][e]

[msg Persona_ID_Text]
[uf 0 5 65278][uf 2 1]Input Persona ID[uf 1 1][e]

[msg Skill_ID_Text]
[uf 0 5 65278][uf 2 1]Input Skill ID[uf 1 1][e]